# Generated by Django 5.1.6 on 2025-03-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0002_intrebare_alter_facultate_options_raspuns"),
    ]

    operations = [
        migrations.CreateModel(
            name="Materie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nume", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name_plural": "materii",
            },
        ),
        migrations.AlterModelOptions(
            name="intrebare",
            options={"verbose_name_plural": "intrebari"},
        ),
        migrations.AlterModelOptions(
            name="raspuns",
            options={"verbose_name_plural": "raspunsuri"},
        ),
        migrations.RenameField(
            model_name="intrebare",
            old_name="text",
            new_name="text_intrebare",
        ),
        migrations.RenameField(
            model_name="raspuns",
            old_name="text",
            new_name="text_raspuns",
        ),
        migrations.RemoveField(
            model_name="raspuns",
            name="scor",
        ),
        migrations.AddField(
            model_name="facultate",
            name="materii",
            field=models.ManyToManyField(to="universities.materie"),
        ),
    ]
