# Generated by Django 5.1.6 on 2025-03-05 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0003_materie_alter_intrebare_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="raspuns",
            name="intrebare",
        ),
        migrations.DeleteModel(
            name="Intrebare",
        ),
        migrations.DeleteModel(
            name="Raspuns",
        ),
    ]
