# Generated by Django 5.1.6 on 2025-03-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0004_remove_raspuns_intrebare_delete_intrebare_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nume", models.CharField(max_length=100)),
                ("tip", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="facultate",
            name="programe",
            field=models.ManyToManyField(to="universities.program"),
        ),
    ]
