# Generated by Django 5.1.6 on 2025-03-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0005_program_facultate_programe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facultate",
            name="materii",
        ),
        migrations.AddField(
            model_name="program",
            name="materii",
            field=models.ManyToManyField(to="universities.materie"),
        ),
    ]
