# Generated by Django 5.1.6 on 2025-03-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0008_rename_locatie_facultate_adresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="facultate",
            name="oras",
            field=models.CharField(default="Bucuresti", max_length=200),
            preserve_default=False,
        ),
    ]
