# Generated by Django 5.1.6 on 2025-03-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0009_facultate_oras"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facultate",
            name="oras",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
