# Generated by Django 5.1.6 on 2025-03-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0010_alter_facultate_oras"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facultate",
            name="adresa",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="facultate",
            name="programe",
            field=models.ManyToManyField(blank=True, to="universities.program"),
        ),
    ]
