# Generated by Django 5.1.6 on 2025-03-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0011_alter_facultate_adresa_alter_facultate_programe"),
    ]

    operations = [
        migrations.CreateModel(
            name="Domeniu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nume", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "domenii",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nume", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "domenii",
            },
        ),
        migrations.AddField(
            model_name="facultate",
            name="buget_camin",
            field=models.DecimalField(
                blank=True, decimal_places=0, default=0, max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="facultate",
            name="buget_taxa",
            field=models.DecimalField(
                blank=True, decimal_places=0, default=0, max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="facultate",
            name="domenii",
            field=models.ManyToManyField(blank=True, to="universities.domeniu"),
        ),
        migrations.AddField(
            model_name="facultate",
            name="skilluri",
            field=models.ManyToManyField(blank=True, to="universities.skill"),
        ),
    ]
