# Generated by Django 5.1.6 on 2025-03-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0012_domeniu_skill_facultate_buget_camin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplexitateDosar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nume", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "complexitate dosar",
            },
        ),
        migrations.CreateModel(
            name="TimpNecesar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nume", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "timp necesar",
            },
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={"verbose_name_plural": "skills"},
        ),
        migrations.AddField(
            model_name="facultate",
            name="cu_admitere",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="facultate",
            name="cu_camin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="facultate",
            name="complexitate_dosar",
            field=models.ManyToManyField(
                blank=True, to="universities.complexitatedosar"
            ),
        ),
        migrations.AddField(
            model_name="facultate",
            name="timp_necesar",
            field=models.ManyToManyField(blank=True, to="universities.timpnecesar"),
        ),
    ]
