# Generated by Django 5.1.6 on 2025-03-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "universities",
            "0013_complexitatedosar_timpnecesar_alter_skill_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Pasiune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nume", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "pasiuni",
            },
        ),
    ]
