# Generated by Django 5.1.6 on 2025-03-28 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0014_pasiune"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="complexitatedosar",
            options={"verbose_name_plural": "complexitate_dosar"},
        ),
        migrations.AlterModelOptions(
            name="timpnecesar",
            options={"verbose_name_plural": "timp_necesar"},
        ),
    ]
