# Generated by Django 5.1.6 on 2025-03-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0015_alter_complexitatedosar_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipareOlimpiade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tip_participare", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name_plural": "participari_olimpiade",
            },
        ),
        migrations.AddField(
            model_name="facultate",
            name="participare_olimpiade",
            field=models.ManyToManyField(
                blank=True, to="universities.participareolimpiade"
            ),
        ),
    ]
